# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-30 10:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Households',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Longitude', models.FloatField()),
                ('Latitude', models.FloatField()),
                ('Income', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Members',
            fields=[
                ('M_id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=250)),
                ('Gender', models.CharField(max_length=10)),
                ('Age', models.IntegerField()),
                ('Hid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pallevelugu.Households')),
            ],
        ),
    ]
