# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-30 11:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pallevelugu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cropping',
            fields=[
                ('C_id', models.AutoField(primary_key=True, serialize=False)),
                ('season', models.CharField(max_length=20)),
                ('Crop', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Farms',
            fields=[
                ('F_id', models.AutoField(primary_key=True, serialize=False)),
                ('Area', models.FloatField()),
                ('H_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pallevelugu.Members')),
            ],
        ),
        migrations.AddField(
            model_name='cropping',
            name='Area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='pallevelugu.Farms'),
        ),
        migrations.AddField(
            model_name='cropping',
            name='F_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='pallevelugu.Farms'),
        ),
    ]
