# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-30 11:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pallevelugu', '0002_auto_20170830_1111'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wells',
            fields=[
                ('W_id', models.AutoField(primary_key=True, serialize=False)),
                ('Yield', models.CharField(max_length=200)),
                ('Depth', models.IntegerField()),
                ('Latitude', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='pallevelugu.Households')),
                ('Longitude', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='pallevelugu.Households')),
            ],
        ),
        migrations.CreateModel(
            name='Yields',
            fields=[
                ('Y_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('Well_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='pallevelugu.Wells')),
                ('Yield', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='pallevelugu.Wells')),
            ],
        ),
    ]
