# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-12 08:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pallevelugu', '0003_wells_yields'),
    ]

    operations = [
        migrations.RenameField(
            model_name='households',
            old_name='id',
            new_name='tid',
        ),
        migrations.RenameField(
            model_name='members',
            old_name='M_id',
            new_name='id',
        ),
        migrations.AddField(
            model_name='households',
            name='Hid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='pallevelugu.Members'),
        ),
        migrations.AlterField(
            model_name='farms',
            name='H_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pallevelugu.Households'),
        ),
        migrations.AlterField(
            model_name='members',
            name='Hid',
            field=models.IntegerField(),
        ),
    ]
