# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-13 11:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pallevelugu', '0006_auto_20170913_1116'),
    ]

    operations = [
        migrations.CreateModel(
            name='latlong',
            fields=[
                ('Lid', models.AutoField(primary_key=True, serialize=False)),
                ('Longitude', models.DecimalField(decimal_places=10, max_digits=20)),
                ('Latitude', models.DecimalField(decimal_places=10, max_digits=20)),
                ('Fid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='pallevelugu.Farms')),
            ],
        ),
    ]
