# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-13 11:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pallevelugu', '0007_latlong'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='yields',
            name='Well_id',
        ),
        migrations.RemoveField(
            model_name='yields',
            name='Yield',
        ),
        migrations.AlterField(
            model_name='wells',
            name='Latitude',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='pallevelugu.Latlong'),
        ),
        migrations.AlterField(
            model_name='wells',
            name='Longitude',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='pallevelugu.Latlong'),
        ),
        migrations.DeleteModel(
            name='Yields',
        ),
    ]
