# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-13 13:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pallevelugu', '0008_auto_20170913_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wells',
            name='Latitude',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='pallevelugu.Latlong'),
        ),
        migrations.AlterField(
            model_name='wells',
            name='Longitude',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='pallevelugu.Latlong'),
        ),
    ]
