# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-14 17:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pallevelugu', '0009_auto_20170913_1335'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cropping',
            name='Area',
        ),
        migrations.RemoveField(
            model_name='cropping',
            name='F_id',
        ),
        migrations.RemoveField(
            model_name='latlong',
            name='Fid',
        ),
        migrations.RemoveField(
            model_name='wells',
            name='Yield',
        ),
        migrations.AddField(
            model_name='farms',
            name='season',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='wells',
            name='M_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='pallevelugu.Members'),
        ),
        migrations.AlterField(
            model_name='farms',
            name='H_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pallevelugu.Members'),
        ),
        migrations.AlterField(
            model_name='wells',
            name='Latitude',
            field=models.DecimalField(decimal_places=10, max_digits=20),
        ),
        migrations.AlterField(
            model_name='wells',
            name='Longitude',
            field=models.DecimalField(decimal_places=10, max_digits=20),
        ),
        migrations.DeleteModel(
            name='Cropping',
        ),
        migrations.DeleteModel(
            name='latlong',
        ),
    ]
