# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-14 17:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pallevelugu', '0011_farms_crop'),
    ]

    operations = [
        migrations.AddField(
            model_name='farms',
            name='Latitude',
            field=models.DecimalField(decimal_places=10, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='farms',
            name='Longitude',
            field=models.DecimalField(decimal_places=10, max_digits=20, null=True),
        ),
    ]
