# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-15 06:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pallevelugu', '0012_auto_20170914_1734'),
    ]

    operations = [
        migrations.RenameField(
            model_name='farms',
            old_name='Latitude',
            new_name='aLatitude',
        ),
        migrations.RenameField(
            model_name='farms',
            old_name='Longitude',
            new_name='aLongitude',
        ),
        migrations.AddField(
            model_name='farms',
            name='bLatitude',
            field=models.DecimalField(decimal_places=10, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='farms',
            name='bLongitude',
            field=models.DecimalField(decimal_places=10, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='farms',
            name='cLatitude',
            field=models.DecimalField(decimal_places=10, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='farms',
            name='cLongitude',
            field=models.DecimalField(decimal_places=10, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='farms',
            name='dLatitude',
            field=models.DecimalField(decimal_places=10, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='farms',
            name='dLongitude',
            field=models.DecimalField(decimal_places=10, max_digits=20, null=True),
        ),
    ]
