# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-06 09:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pallevelugu', '0013_auto_20170915_0617'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='Audio',
            field=models.FileField(max_length=200, null=True, upload_to='mp3/'),
        ),
        migrations.AddField(
            model_name='members',
            name='Photos',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
