# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-06 09:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pallevelugu', '0014_auto_20171006_0937'),
    ]

    operations = [
        migrations.AddField(
            model_name='wells',
            name='Audio',
            field=models.FileField(max_length=200, null=True, upload_to='mp3/'),
        ),
        migrations.AddField(
            model_name='wells',
            name='AvgWaTyield',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='wells',
            name='Pic',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
