# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-06 12:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pallevelugu', '0015_auto_20171006_0954'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('M_id', models.AutoField(primary_key=True, serialize=False)),
                ('season', models.CharField(max_length=20, null=True)),
                ('crop', models.CharField(max_length=20, null=True)),
                ('F_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='pallevelugu.Farms')),
            ],
        ),
        migrations.RemoveField(
            model_name='wells',
            name='Audio',
        ),
        migrations.RemoveField(
            model_name='wells',
            name='Pic',
        ),
    ]
