# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-06 13:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pallevelugu', '0016_auto_20171006_1259'),
    ]

    operations = [
        migrations.AddField(
            model_name='crop',
            name='profit',
            field=models.IntegerField(null=True),
        ),
    ]
