# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-06 14:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pallevelugu', '0017_crop_profit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='households',
            name='Hid',
        ),
        migrations.AddField(
            model_name='members',
            name='Income',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='members',
            name='Latitude',
            field=models.DecimalField(decimal_places=10, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='members',
            name='Longitude',
            field=models.DecimalField(decimal_places=10, max_digits=20, null=True),
        ),
        migrations.DeleteModel(
            name='Households',
        ),
    ]
