# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-07 04:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pallevelugu', '0018_auto_20171006_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='Members',
            field=models.IntegerField(null=True),
        ),
    ]
