# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-12 04:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pallevelugu', '0019_members_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='Audio',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='members',
            name='Photos',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
