# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-24 05:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pallevelugu', '0020_auto_20171012_0444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='Audio',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='members',
            name='Photos',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
