# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-31 16:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pallevelugu', '0021_auto_20171024_0555'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crop',
            name='F_id',
        ),
        migrations.DeleteModel(
            name='Crop',
        ),
    ]
