# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-02 04:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pallevelugu', '0023_crop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='Photos',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
