# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-02 16:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pallevelugu', '0024_auto_20171102_0415'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dealer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantity', models.IntegerField(null=True)),
                ('MarketPrice', models.IntegerField(null=True)),
                ('H_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pallevelugu.Members')),
                ('crop', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pallevelugu.Crop')),
            ],
        ),
        migrations.CreateModel(
            name='Medicare',
            fields=[
                ('mid', models.AutoField(primary_key=True, serialize=False)),
                ('Disease', models.CharField(max_length=200, null=True)),
                ('Vaccine', models.CharField(max_length=200, null=True)),
                ('Hospital', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Vill',
            fields=[
                ('D_id', models.AutoField(primary_key=True, serialize=False)),
                ('Village', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='medicare',
            name='Did',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='pallevelugu.Vill'),
        ),
    ]
