# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-02 20:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pallevelugu', '0025_auto_20171102_1609'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='members',
            name='Audio',
        ),
        migrations.AlterField(
            model_name='dealer',
            name='crop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='pallevelugu.Crop'),
        ),
        migrations.AlterField(
            model_name='medicare',
            name='Hospital',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=1),
        ),
        migrations.AlterField(
            model_name='members',
            name='Photos',
            field=models.ImageField(null=True, upload_to='media/'),
        ),
    ]
