# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-03 13:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pallevelugu', '0026_auto_20171102_2024'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='AadharNo',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
