# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-04 17:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pallevelugu', '0027_members_aadharno'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediUpdates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updates', models.CharField(max_length=2000000000000, null=True)),
            ],
        ),
    ]
